import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignedOut, SignInButton, SignedIn, UserButton } from "@clerk/nextjs";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className="h-full">
        <body className={`${inter.className} p-5`}>
          <header className="flex justify-between mb-10">
            <div className="flex items-center gap-7">
              <Link href="/"><h1>Word Warehouse 📦</h1></Link>
              <Link href="/words">My words</Link>
            </div>
            <div className="flex items-center gap-3">
              <SignedIn>
                <UserButton showName />
              </SignedIn>
              <SignedOut>
                <SignInButton />
              </SignedOut>
            </div>
          </header>
          <div>
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
